[project]
name = "mastering-python"
version = "0.1.0"
description = "A project to demonstrate some of the best practices in python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "numpy>=2.2.5",
    "pre-commit>=4.2.0",
]
